# Generated by Django 5.1.7 on 2025-04-06 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Package Name')),
                ('net_unit', models.IntegerField(verbose_name='Units in the package')),
                ('weight', models.FloatField(verbose_name='Total package weight')),
                ('package_type', models.CharField(choices=[('bag', 'Bag'), ('drum', 'Drum')], default='bag', max_length=10, verbose_name='Package type')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('code', models.CharField(max_length=10, verbose_name='Product Code')),
                ('sales_price', models.FloatField(verbose_name='Product sales price')),
                ('cost_per_unit', models.FloatField(verbose_name='Product cost per unit')),
                ('sale_ok', models.BooleanField(default=True, verbose_name='Sale ok?')),
                ('purchase_ok', models.BooleanField(default=True, verbose_name='Purchase Ok?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='product.productcategory')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='product.packaging')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=300)),
                ('lot_code', models.CharField(max_length=300)),
                ('weight', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.producttemplate')),
            ],
        ),
    ]
