# Generated by Django 5.1.7 on 2025-04-09 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_unit', models.FloatField()),
                ('finished_product_qunatity', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_bom', to='product.producttemplate')),
                ('raw_material', models.ForeignKey(limit_choices_to={'category__name': 'Raw Materials'}, on_delete=django.db.models.deletion.CASCADE, to='product.producttemplate')),
            ],
        ),
    ]
