# Generated by Django 5.1.7 on 2025-04-06 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('employee', '0001_initial'),
        ('product', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('mo_number', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('produced_qty', models.IntegerField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('in-process', 'In Process'), ('confirmed', 'Confirmed'), ('done', 'Done')], default='draft', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='contact.contacts')),
                ('location_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mo_raw_material_location', to='stock.stocklocation')),
                ('location_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mo_finished_product_location', to='stock.stocklocation')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employee.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacture_product', to='product.producttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingOrderRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mo_raw_materials', to='manufacture.manufacture')),
                ('raw_material', models.ForeignKey(limit_choices_to={'category__name': 'Raw Materials'}, on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='product.producttemplate')),
            ],
        ),
    ]
